import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-medicare-advantage-quality-bonus-revenue-reconciliation",
  "engine": "recovery",
  "title": "Medicare Advantage Quality Bonus Revenue Reconciliation",
  "shortTitle": "Medicare Advantage Quality Bonus Revenue Reconciliation",
  "tagline": "Reconcile quality-bonus and rebate revenue to rating results, enrollment geography, and CMS payment mechanics.",
  "industry": "Medicare Advantage Finance",
  "buyer": "Medicare Advantage plans",
  "uiPort": 4642,
  "apiPort": 5642,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Medicare Advantage Quality Bonus Revenue Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence in one accountable workflow. Reconcile quality-bonus and rebate revenue to rating results, enrollment geography, and CMS payment mechanics.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Medicare Advantage Quality Bonus Revenue Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("contract-and-segment-registry","MAQ01","Contract and segment registry","Execute contract and segment registry using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed contract and segment registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Contract and segment registry Reference","text","MAQ01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("star-measure-ingestion","MAQ02","Star measure ingestion","Execute star measure ingestion using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed star measure ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Star measure ingestion Reference","text","MAQ02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("cut-point-version-control","MAQ03","Cut-point version control","Execute cut-point version control using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed cut-point version control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Cut-point version control Reference","text","MAQ03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("enrollment-month-reconciliation","MAQ04","Enrollment month reconciliation","Execute enrollment month reconciliation using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed enrollment month reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Enrollment month reconciliation Reference","text","MAQ04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("county-benchmark-mapping","MAQ05","County benchmark mapping","Execute county benchmark mapping using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed county benchmark mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","County benchmark mapping Reference","text","MAQ05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("quality-bonus-factor-calculation","MAQ06","Quality bonus factor calculation","Execute quality bonus factor calculation using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed quality bonus factor calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Quality bonus factor calculation Reference","text","MAQ06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("rebate-percentage-validation","MAQ07","Rebate percentage validation","Execute rebate percentage validation using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed rebate percentage validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Rebate percentage validation Reference","text","MAQ07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("double-bonus-county-logic","MAQ08","Double-bonus county logic","Execute double-bonus county logic using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed double-bonus county logic decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Double-bonus county logic Reference","text","MAQ08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("new-plan-treatment","MAQ09","New-plan treatment","Execute new-plan treatment using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed new-plan treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","New-plan treatment Reference","text","MAQ09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("low-enrollment-plan-treatment","MAQ10","Low-enrollment plan treatment","Execute low-enrollment plan treatment using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed low-enrollment plan treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Low-enrollment plan treatment Reference","text","MAQ10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("payment-report-ingestion","MAQ11","Payment report ingestion","Execute payment report ingestion using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed payment report ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Payment report ingestion Reference","text","MAQ11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("expected-revenue-calculation","MAQ12","Expected revenue calculation","Execute expected revenue calculation using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed expected revenue calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Expected revenue calculation Reference","text","MAQ12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("cms-variance-case-workflow","MAQ13","CMS variance case workflow","Execute cms variance case workflow using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed cms variance case workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","CMS variance case workflow Reference","text","MAQ13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("revenue-true-up-ledger","MAQ14","Revenue true-up ledger","Execute revenue true-up ledger using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed revenue true-up ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Revenue true-up ledger Reference","text","MAQ14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]}),
feature("contract-quality-economics","MAQ15","Contract quality economics","Execute contract quality economics using Star measure results, enrollment, county benchmarks, rebate percentages, quality bonus factors, payment reports, and CMS correspondence.","Produce a governed contract quality economics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Rating Contract","text","Plan / Rating Contract · Standard Case"],["caseReference","Contract quality economics Reference","text","MAQ15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",493750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",597438],["domainDriver","Rating Segment","select","Four-star",["Four-star","Five-star","Low enrollment"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract and segment registry case","Star measure ingestion case","Cut-point version control case","Enrollment month reconciliation case","County benchmark mapping case"]})
]);
